version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 9 20 * *"
      timezone: "Asia/Tokyo"
    target-branch: "develop"
    groups:
      dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "jp.ecuacion.*:*"
